### ISSUE TITLE
project on maven repository

### ISSUE THREAD

**Issue by btwonion** [HttpRafa/BetterFarmland#1]
hello,
a user of my mods asked me to create an extension to your mod. 
I created a telekinesis mod and he want to work your mod with it. 
Is it possible to upload your mod to a maven repo, that i can create a mixin for it?

**Comment by HttpRafa** [comment]
I will upload the mod to a maven repository.

**Comment by btwonion** [comment]
nice thank you

**Comment by HttpRafa** [comment]
While I create a repository you can just use the Modrinth Maven repository.
https://docs.modrinth.com/docs/tutorials/maven/

```
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
```

```
    modApi "maven.modrinth:betterfarmland:1.0.2"
```

**Comment by btwonion** [comment]
okay thank you for you quick answer

**Comment by HttpRafa** [comment]
I have my own [repo](https://repo.httprafa.link/#/releases) ready if you want you can use it now.
```
maven {
    url "https://repo.httprafa.link/releases"
}
```
```
modApi "de.rafael:betterfarmland-fabric:1.0.2"
```

**Comment by btwonion** [comment]
i saw it on your readme.
thank you
